// GENERATED by scripts/build-icon-sprite.mjs — do not edit by hand.
//
// The viewBox of every icon in the page sprite (lib/icons/sprite), without
// the symbol bodies: SpriteIcon needs only this, and it ships to the browser.

export const SPRITE_VIEWBOXES: Record<string, string> = {"solar:bed-linear":"0 0 24 24","solar:bath-linear":"0 0 24 24","lineicons:arrow-all-direction":"0 0 25 25","solar:map-linear":"0 0 24 24","solar:alt-arrow-left-linear":"0 0 24 24","solar:alt-arrow-right-linear":"0 0 24 24","solar:maximize-square-minimalistic-linear":"0 0 24 24","ph:star-fill":"0 0 256 256","ph:fire-fill":"0 0 256 256","ph:tag-fill":"0 0 256 256","ph:crane-tower-fill":"0 0 256 256","ph:heart":"0 0 256 256","ph:heart-fill":"0 0 256 256"};
