import { propertyPath, type LocalizedSlug } from "@/lib/property/propertyUrl";
import { buildUrlsetXml, type SitemapUrl } from "@/lib/seo/sitemapXml";

/**
 * Google attributes an image to the page that hosts it, so every locale URL of
 * a listing lists its photos — but six per URL, not the whole gallery: the
 * file already holds (listings × 7 locales) URLs and each image line is ~240
 * bytes.
 */
export const SITEMAP_IMAGES_PER_URL = 6;

/**
 * The sitemap protocol allows 50 MB, which this never approaches. The ceiling
 * that matters is the 4.5 MB response body of a Vercel function: the route is
 * regenerated by one every hour. Past this budget the photos per URL are cut
 * back until the file fits — a thinner image sitemap beats a 413. Measured on
 * 2026-09-20 against the live dataset (375 listings × 7 locales = 2,625 URLs):
 * six photos per URL is 3.52 MB, five is 3.08 MB, four is 2.61 MB — so the
 * budget currently settles on five (11,648 image entries).
 * When the inventory outgrows even that, split this sitemap per locale.
 */
export const SITEMAP_MAX_BYTES = 3_500_000;

export type PropertySitemapRow = {
  slug: string;
  localizedSlug: LocalizedSlug;
  lastModified: Date;
  /** Canonical, named image URLs in gallery order (see lib/images/propertyImageUrl). */
  images?: string[];
};

function byteLength(s: string): number {
  return new TextEncoder().encode(s).length;
}

export function buildPropertySitemapXml(input: {
  base: string;
  locales: readonly string[];
  rows: PropertySitemapRow[];
  imagesPerUrl?: number;
  maxBytes?: number;
}): string {
  const { base, locales, rows } = input;
  const maxBytes = input.maxBytes ?? SITEMAP_MAX_BYTES;
  let perUrl = Math.max(0, input.imagesPerUrl ?? SITEMAP_IMAGES_PER_URL);

  for (;;) {
    const urls: SitemapUrl[] = [];
    for (const locale of locales) {
      for (const row of rows) {
        urls.push({
          loc: `${base}${propertyPath(locale, row.slug, row.localizedSlug)}`,
          lastmod: row.lastModified,
          ...(perUrl > 0 && row.images?.length ? { images: row.images.slice(0, perUrl) } : {}),
        });
      }
    }
    const xml = buildUrlsetXml(urls);
    if (perUrl === 0 || byteLength(xml) <= maxBytes) return xml;
    perUrl -= 1;
  }
}
