import type { Metadata } from 'next'
import { resolveLocalizedString } from './localized'

type LocalizedField = { en?: string; ru?: string; uk?: string; sq?: string; it?: string } | null | undefined

export type LandingSeoObject = {
  metaTitle?: LocalizedField
  metaDescription?: LocalizedField
  ogTitle?: LocalizedField
  ogDescription?: LocalizedField
  ogImage?: { asset?: { url?: string } }
  keywords?: LocalizedField
  twitterTitle?: LocalizedField
  twitterDescription?: LocalizedField
  canonicalUrl?: string | LocalizedField
  noIndex?: boolean
  noFollow?: boolean
}

export type LandingSeo = LandingSeoObject | null

type SiteDefaultSeo = {
  metaTitle?: LocalizedField
  metaDescription?: LocalizedField
  noIndex?: boolean
  noFollow?: boolean
} | null

const TEMPLATE_TITLE = 'Domlivo - A Real Estate Framer Template'
const TEMPLATE_DESCRIPTION = 'Generated by create next app'

function resolveCanonicalUrl(
  raw: LandingSeoObject['canonicalUrl'] | null | undefined,
  locale: string,
): string | undefined {
  if (!raw) return undefined
  if (typeof raw === 'string') return raw
  const val = resolveLocalizedString(raw as never, locale)
  return val?.trim() ? val.trim() : undefined
}

function resolveKeywords(raw: LandingSeoObject['keywords'] | null | undefined, locale: string): string[] | undefined {
  const str = resolveLocalizedString(raw as never, locale)
  const items = str
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
  return items.length ? items : undefined
}

/** Canonical landingPage.seo → Next Metadata (landing-home + inner city landings). */
export function buildLandingMetadata(
  landingSeo: LandingSeo | undefined,
  siteDefaultSeo: SiteDefaultSeo | undefined,
  locale: string,
): Metadata {
  const title =
    resolveLocalizedString(landingSeo?.metaTitle as never, locale) ||
    resolveLocalizedString(siteDefaultSeo?.metaTitle as never, locale) ||
    TEMPLATE_TITLE

  const description =
    resolveLocalizedString(landingSeo?.metaDescription as never, locale) ||
    resolveLocalizedString(siteDefaultSeo?.metaDescription as never, locale) ||
    TEMPLATE_DESCRIPTION

  const ogTitle = resolveLocalizedString(landingSeo?.ogTitle as never, locale) || title
  const ogDescription = resolveLocalizedString(landingSeo?.ogDescription as never, locale) || description

  const ogImageUrl = (landingSeo?.ogImage as { asset?: { url?: string } })?.asset?.url
  const ogImageAbsolute = ogImageUrl && ogImageUrl.startsWith('http') ? ogImageUrl : undefined

  const twitterTitle = resolveLocalizedString(landingSeo?.twitterTitle as never, locale) || ogTitle
  const twitterDescription =
    resolveLocalizedString(landingSeo?.twitterDescription as never, locale) || ogDescription

  const canonical = resolveCanonicalUrl(landingSeo?.canonicalUrl, locale)
  const noIndex = landingSeo?.noIndex ?? siteDefaultSeo?.noIndex ?? false
  const noFollow = landingSeo?.noFollow ?? siteDefaultSeo?.noFollow ?? false

  return {
    title,
    description,
    keywords: resolveKeywords(landingSeo?.keywords, locale),
    alternates: canonical ? { canonical } : undefined,
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      ...(ogImageAbsolute && {
        images: [{ url: ogImageAbsolute, width: 1200, height: 630, alt: ogTitle }],
      }),
    },
    twitter: {
      card: ogImageAbsolute ? 'summary_large_image' : 'summary',
      title: twitterTitle,
      description: twitterDescription,
      ...(ogImageAbsolute ? { images: [ogImageAbsolute] } : {}),
    },
    robots: noIndex || noFollow ? { index: !noIndex, follow: !noFollow } : undefined,
  }
}
