import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";
import { routing } from "@/i18n/routing";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Domlivo - A Real Estate Framer Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale?: string };
}>) {
  const locale =
    typeof params?.locale === "string" &&
    routing.locales.includes(params.locale)
      ? params.locale
      : routing.defaultLocale;
  return (
    <html lang={locale}>
      <body
        className={`${font.className} bg-white dark:bg-black antialiased transition-colors duration-300 ease-out`}
      >
        <NextTopLoader color="#07be8a" />
        <ThemeProvider
          attribute="class"
          enableSystem={true}
          defaultTheme="light"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
