import { describe, expect, it } from 'vitest'
import {
  acKwhPerMonth,
  annualUtilitiesEur,
  calculateUtilities,
  electricityEur,
  ELECTRICITY,
  waterEur,
} from './utilities'

/**
 * The reference values come from the research repo's own engine
 * (`12-ai-database/data/roi_tables.md`, generated by calc_engine.py). If this
 * port drifts from those, the site and the knowledge base would quote
 * different numbers for the same apartment — which is exactly the failure the
 * citations are meant to prevent.
 *
 * One deliberate difference: the Python engine hard-codes a rounded 124 kWh
 * for a 12k unit cooling 8 h/day, while this port computes 123.6 from rated
 * input × draw factor so it can answer any size and any number of hours. The
 * gap shows up only with two units running (0.8 kWh, under 0.1 EUR) and the
 * expectations below use the computed figure.
 */
describe('utilities — parity with the research engine', () => {
  const cases: Array<[Parameters<typeof calculateUtilities>[0], number, number]> = [
    [{ city: 'durres', sizeM2: 60, occupants: 2, season: 'winter' }, 457, 111.47],
    [{ city: 'durres', sizeM2: 60, occupants: 2, season: 'summer' }, 437, 109.22],
    [{ city: 'durres', sizeM2: 60, occupants: 2, season: 'shoulder' }, 313, 95.5],
    [{ city: 'durres', sizeM2: 45, occupants: 2, season: 'winter' }, 445, 108.6],
    [{ city: 'durres', sizeM2: 100, occupants: 2, season: 'winter' }, 626, 134.2],
    [{ city: 'tirana', sizeM2: 60, occupants: 2, season: 'winter' }, 457, 109.4],
    [{ city: 'vlore', sizeM2: 60, occupants: 2, season: 'winter' }, 457, 107.9],
    [{ city: 'sarande', sizeM2: 80, occupants: 2, season: 'summer' }, 574, 123.76],
    [{ city: 'shengjin', sizeM2: 100, occupants: 2, season: 'shoulder' }, 338, 99.45],
  ]

  it.each(cases)('%o → %i kWh, %f EUR', (input, kwh, eur) => {
    const result = calculateUtilities(input)
    expect(result.kwhPerMonth).toBe(kwh)
    expect(result.totalEurPerMonth).toBeCloseTo(eur, 1)
  })

  it('matches the per-occupant column for a 60 m² flat in winter', () => {
    const totals = [1, 2, 3, 4].map(
      (occupants) =>
        calculateUtilities({ city: 'durres', sizeM2: 60, occupants, season: 'winter' })
          .totalEurPerMonth,
    )
    expect(totals).toEqual([95.0, 111.5, 128.0, 144.6].map((v) => expect.closeTo(v, 1)))
  })
})

describe('the 700 kWh cliff', () => {
  it('prices the whole month at the higher rate once crossed', () => {
    const below = electricityEur(ELECTRICITY.thresholdKwh)
    const above = electricityEur(ELECTRICITY.thresholdKwh + 1)
    expect(below.aboveThreshold).toBe(false)
    expect(above.aboveThreshold).toBe(true)
    // One extra kWh costs ~9 EUR, not ~0.12: that is the point of the rule.
    expect(above.eur - below.eur).toBeGreaterThan(8)
  })

  it('flags a flat that crosses it', () => {
    const heavy = calculateUtilities({
      city: 'durres',
      sizeM2: 120,
      occupants: 4,
      season: 'winter',
      acHoursPerDay: 12,
      acBtu: 18000,
      acUnits: 2,
    })
    expect(heavy.aboveElectricityThreshold).toBe(true)
    expect(heavy.lines[0].note).toContain('700 kWh threshold')
  })
})

describe('air conditioning', () => {
  it('reproduces the documented 12k BTU scenarios', () => {
    expect(acKwhPerMonth(12000, 8, 'cooling')).toBeCloseTo(124, 0)
    expect(acKwhPerMonth(12000, 8, 'heating')).toBeCloseTo(144, 0)
    expect(acKwhPerMonth(9000, 4, 'cooling')).toBeCloseTo(46, 0)
    expect(acKwhPerMonth(24000, 24, 'heating')).toBeCloseTo(808, 0)
  })

  it('contributes nothing in a shoulder month', () => {
    const shoulder = calculateUtilities({
      city: 'vlore',
      sizeM2: 60,
      occupants: 2,
      season: 'shoulder',
      acHoursPerDay: 12,
    })
    const same = calculateUtilities({ city: 'vlore', sizeM2: 60, occupants: 2, season: 'shoulder' })
    expect(shoulder.kwhPerMonth).toBe(same.kwhPerMonth)
  })
})

describe('water', () => {
  it('uses the city tariff and the fixed fee', () => {
    // Durrës 70+50 lek/m³ + 200 lek, two people at 120 L/day = 7.2 m³.
    expect(waterEur('durres', 2)).toBeCloseTo((7.2 * 120 + 200) / 92.02, 2)
    expect(waterEur('tirana', 2)).toBeLessThan(waterEur('durres', 2))
  })
})

describe('annual weighting', () => {
  it('costs more in Tirana than on the southern coast, because the season is longer', () => {
    const tirana = annualUtilitiesEur({ city: 'tirana', sizeM2: 60, occupants: 2 })
    const saranda = annualUtilitiesEur({ city: 'sarande', sizeM2: 60, occupants: 2 })
    expect(tirana).toBeGreaterThan(saranda)
    // Sanity bound from the research audit: a normal flat is 60–160 EUR/month.
    expect(tirana / 12).toBeGreaterThan(60)
    expect(tirana / 12).toBeLessThan(160)
  })
})
